go_binary(
    name = "clang_proxy",
    srcs = ["clang_proxy.go"],
)

go_binary(
    name = "counter",
    srcs = ["counter.go"],
)

go_binary(
    name = "process_cmd",
    srcs = ["process_cmd.go"],
)
